### ISSUE TITLE
Plan for testing state

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-operator#109]
We want to be able to tear down a MiniCluster and then bring it back up and continue running the jobs. This could also mean changing the size of the cluster (see issue #41). I've figured out how to save state for the current flux instance (thanks @garlick ) and my plan is the following (not sure how far I'll get in what time period, but started work today):

 - [x] Saving state of the jobs queue and metadata, after runs are complete (between two MiniClusters) #110 
 - [x] Saving state of the jobs queue and metadata, pausing a queue in the middle and resuming. https://github.com/flux-framework/flux-operator/pull/115
 - [x] The same, but increasing or decreasing the size of the MiniCluster https://github.com/flux-framework/flux-operator/pull/115
 - [ ] Saving state of the jobs queue and metadata, and including filesystem (storage) assets.

And after the last bullet, the hard part will be figuring out how to plug this into actual workflows. E.g., we can hard code steps /jobs to run on minicluster 1 and then the same for minicluster 2 (to pick something up) but more ideally this would be part of a DAG, and logic implemented to figure out the miniclusters to create and when. I might experiment with a custom Snakemake executor and the DAG generated there - honestly I'm having a hard time finding workflows that are "worthy of an HPC paper." (the biosciences ones on the other hand tend to be very reproducible). So far I've done the following:

 - Added an "archive->path" flag that indicates a custom state directory (requires a persistent volume)
 - Creating an example with both minicluster YAMLs (with interactive mode) and the flux-operator Python SDK (submits a bunch of jobs, totally programmatic)

For the second bullet, this the the wisdom I need (and need to figure out executing commands to the broker pod to do this, likely as a client function of the Flux Operator Python SDK

```
$ flux queue disable "Pausing minicluster"
Job submission is disabled: Pausing minicluster
And then I can disable scheduling (e.g., don't schedule existing jobs in the queue)
$ flux queue stop
Scheduling is stopped
```

I have the first part implemented - I'm getting an error on the state directory:

```console
🌀 sudo -u flux -E PYTHONPATH=/usr/lib/flux/python3.8:/code -E PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -E HOME=/home/flux flux broker --config-path /etc/flux/config -Scron.directory=/etc/flux/system/cron.d   -Stbon.fanout=256   -Srundir=/run/flux -Sbroker.rc2_none    -Sstatedir=/state/archive   -Slocal-uri=local:///run/flux/local  -Slog-stderr-level=6    -Slog-stderr-mode=local
broker.info[0]: start: none->join 15.622ms
broker.info[0]: parent-none: join->init 0.040601ms
content-sqlite.err[0]: setting sqlite 'journal_mode' pragma: locking protocol(15)
content-sqlite.crit[0]: module exiting abnormally
broker.err[0]: rc1.0: flux-module: broker.insmod: Invalid argument
broker.err[0]: rc1.0: /etc/flux/rc1 Exited (rc=1) 10.4s
broker.info[0]: rc1-fail: init->shutdown 10.3528s
broker.info[0]: children-none: shutdown->finalize 0.046227ms
broker.info[0]: rc3.0: running /etc/flux/rc3.d/01-sched-fluxion
broker.err[0]: rc3.0: flux: Error commiting finish event: No service matching kvs.commit is registered
broker.err[0]: rc3.0: flux-content: content.flush: Function not implemented
broker.err[0]: rc3.0: flux-module: broker.rmmod content-sqlite: No such file or directory
broker.err[0]: rc3.0: /etc/flux/rc3 Exited (rc=1) 0.2s
broker.info[0]: rc3-fail: finalize->goodbye 0.151724s
broker.info[0]: goodbye: goodbye->exit 0.048091ms
```
I suspect it's some kind of permissions error or similar - going for a run now but will compare the working vs. not working directories when I get back.

**Comment by vsoch** [comment]
okay here are the permissions for a working `/var/lib/flux`
```console
root@flux-sample-0:/code# ls -l /var/lib/flux/
total 244
-rw-r--r-- 1 flux flux   4096 Mar 12 01:50 content.sqlite
-rw-r--r-- 1 flux flux 189552 Mar 12 01:50 content.sqlite-wal
-rw-r--r-- 1 flux flux   4096 Mar 12 01:50 job-archive.sqlite
-rw-r--r-- 1 flux flux  32768 Mar 12 01:50 job-archive.sqlite-shm
-rw-r--r-- 1 flux flux  12392 Mar 12 01:50 job-archive.sqlite-wal
```
and for the non working shown above:

```console
$ kubectl exec -it -n flux-operator flux-sample-1-lp76q -- ls -l /state/archive
total 20
-rw-r--r-- 1 flux 999 20480 Mar 11 23:47 content.sqlite
-rw-r--r-- 1 flux 999     0 Mar 11 23:47 content.sqlite-shm
-rw-r--r-- 1 flux 999     0 Mar 11 23:47 content.sqlite-wal
```
I think we are seeing the same issues we've seen with most storage - that it's required to be bound as root (and then we can't change permission after in standard ways). Likely we will need to do a copy of files before and after to mimic writing them there in the first place - I'll test this next.

**Comment by vsoch** [comment]
@grondo @garlick @trws do you have any insight to this error message? For all changes of state, there are always a few jobs that I can't run attach because of this.


```console
$ flux job attach ƒrGXgioy 
142.227s: job.exception type=exec severity=0 failed to create guest ns: No such file or directory
142.410s: job.exception type=scheduler-restart severity=0 failed to reallocate R for running job
flux-job: flux_job_event_watch_get: Operation not supported
```
Could it be related to the order I do things (I did flux queue disable then flux queue stop - I thought the first would stop scheduling and the first would stop everything. Was there some wait that I needed to do (and didn't?) or something?

**Comment by grondo** [comment]
Flux doesn't support restart with running jobs at this time. Make sure all running jobs have been canceled or completed before the instance shuts down. I think the problem here is that the job in question is still running at shutdown of the original instance?

**Comment by vsoch** [comment]
Oh gotcha. So there is no way to say "wait until the jobs are finished" - I just need to stop the queue and manually wait for that? Is there a single, one off command that can give me this answer programmatically?

**Comment by garlick** [comment]
I'm not too sure why Flux isn't doing this for you.  It runs this little script when it begins to shut down:
```
flux queue stop --quiet --all --nocheckpoint
flux cancel --user=all --quiet --states RUN
flux queue idle --quiet
```

**Comment by vsoch** [comment]
ahhh I forgot the idle! That's my bad :_) I'll test that when I get back for my run. That is exactly what we'd like! Thank you @garlick !

**Comment by grondo** [comment]
It is difficult to tell the order of operations but are you perhaps calling `flux dump` before the shutdown? If that is the case, you should instead be setting the `content.dump` attribute so that this is handled for you in `rc3`.

**Comment by vsoch** [comment]
No I'm not - in this particular case the commands to stop/pause the queue from first, and the dump happens when we delete the minicluster (a post stop hook).

And oh - you are saying that attribute can be set for the broker and it will always save to `content.dump` ? That's awesome!! I can add it along with the attribute to restore here https://github.com/flux-framework/flux-operator/blob/d9036c25965563bf6e815e60d1f51876bc62f4a9/controllers/flux/templates/wait.sh#L87 and totally nix the post stop hook! :raised_hands:

**Comment by grondo** [comment]
I believe you would do something like `-Scontent.dump={{.Archive.Path}}` and `rc3` will take care of writing out the dumpfile to whatever `.Archive.path`  resolves to, if that makes sense (of course, substitute whatever property here if necessary)

**Comment by vsoch** [comment]
On a second thought - I'm going to hold off for now because the hook ensures that the command will be run right before pod termination, and if the broker is doing something separately it could be the entire thing doesn't save. So I'll take a mental note of this, but keep the implementation as is for now.

**Comment by vsoch** [comment]
okay so I did:

```
# I know you said this wasn't necessary but I figure it doesn't hurt?
flux queue disable "Pausing minicluster to save state"

# This should wait for running jobs to finish?
flux queue idle

# and then stop
flux queue stop
```

And I still have those failed jobs:

![image](https://user-images.githubusercontent.com/814322/224866895-f685a262-987d-4ebc-a785-e57c9824f217.png)

Did I mess up the order again? I'd like to be able to say "finish the jobs that are running - don't schedule new ones" and then to wait, and for the shutdown to be successful (without losing / failing jobs like I currently have). Sorry if I missed something you already told me.

**Comment by vsoch** [comment]
oh this is interesting - those jobs are failing before I've issued any commands. So this isn't an issue of saving state - they are failing for some other reason!

**Comment by vsoch** [comment]
Okay I can confirm on the first instance - jobs have status CD or S:

![image](https://user-images.githubusercontent.com/814322/224870952-d717421b-30b3-4d5b-b581-e942c75df72e.png)

But when we load the archive, 2 of those jobs (that were previously CD) are now F

![image](https://user-images.githubusercontent.com/814322/224870989-237a49a5-aee5-4abe-b4bb-f2156583f131.png)

So likely it is something related to that transition that causes this:

```
$ flux job attach ƒrGXgioy 
142.227s: job.exception type=exec severity=0 failed to create guest ns: No such file or directory
142.410s: job.exception type=scheduler-restart severity=0 failed to reallocate R for running job
flux-job: flux_job_event_watch_get: Operation not supported
```

**Comment by garlick** [comment]
It should be 1) stop, 2) idle, just so that while the running jobs are finishing, new jobs aren't scheduled as the resources become idle.

So maybe as @grondo suggested the dump is getting saved before Flux is done, and we're restarting from state that is an earlier snapshot than the final one?

**Comment by vsoch** [comment]
> So maybe as @grondo suggested the dump is getting saved before Flux is done, and we're restarting from state that is an earlier snapshot than the final one?

No that's not possible, because the dump happens as a post exec hook - I would have to terminate the cluster pods. When I'm running these commands nothing is being terminated - I run all of them, wait for them to finish (even add sleep) and then the request to delete the MiniCluster goes in, and that's when the dump is requested.

**Comment by vsoch** [comment]
I'll try doing the stop before idle - I wasn't doing that! brb.

**Comment by vsoch** [comment]
Okay update - running stop before idle didn't change the outcome. And this time I removed the queue disable since that's not necessary.

**Comment by vsoch** [comment]
I’ll try adding a ridiculously long sleep before deletion to see if it’s related to timing.

**Comment by vsoch** [comment]
okay so sorry for being an idiot - I had a syntax error so the idle command wasn't properly executing! Everything looks good now! Thanks for the help (and sorry for being dumb). :laughing:

**Comment by garlick** [comment]
> the dump happens as a post exec hook

Just so I understand, is the dump being requested by `flux shutdown --dump`?

**Comment by vsoch** [comment]
No - just flux dump to the instance https://github.com/flux-framework/flux-operator/blob/d9036c25965563bf6e815e60d1f51876bc62f4a9/controllers/flux/state.go#L60. Should I do shutdown instead?

**Comment by garlick** [comment]
Yes - that, or set the broker attribute that @grondo mentioned.  Otherwise the dump won't contain the final checkpoint.  That would explain the problems you were reporting.

**Comment by vsoch** [comment]
> Yes - that, or set the broker attribute that @grondo mentioned. Otherwise the dump won't contain the final checkpoint. That would explain the problems you were reporting.

Okay I'll test / update that command to run a shutdown with `--dump` and I'll add the archive to the broker attribute so it knows where to do that (assuming that's a boolean flag and not an option argument that should be followed by the archive path).

**Comment by vsoch** [comment]
okay I think we are good with this issue - I've been able to save state (and avoid the errors above). The "save the filesystem assets" just comes down to mounting the same volume again. Thanks the help @grondo @garlick !
