### ISSUE TITLE
Worker pod termination

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-operator#151]
We currently don't take any steps to terminate worker pods when the broker stops, and ideally we would be able to flag all the worker pods as Completed when the broker pod is. If anyone has ideas please comment here. This issue was originally discussed (with a few ideas) here: https://github.com/kubernetes-sigs/kueue/issues/716

**Comment by alculquicondor** [comment]
One recommendation by @ahg-g is to use https://github.com/kubernetes-sigs/jobset to separate the broken into its own job.

However, the migration might not be worth if you plan to eventually use https://github.com/kubernetes/kubernetes/issues/117600

So, what is the right solution? The question you need to answer is whether it makes sense for the broker to be significantly different from the rest. For example, workers might need GPUs, but not the broker, or the broker might need more/less CPU.

If the answer is that the broker could be different, then jobset is the right answer. If not, then Indexed Job will be simpler and faster to manage.

**Comment by vsoch** [comment]
The main impetus (aside from the broker having different logic, which you can see [tangled up here](https://github.com/flux-framework/flux-operator/blob/240a4e04571766e9ccc5e484274833df89130944/controllers/flux/templates/wait.sh#L282)) is controlling order / timing of creation - it would be really nice for the broker to reliably come up first! That said, I don't see that this is possible yet? It looks like the potential contents of the list in `replicatedJobs` come up at the same time. 

For the termination issue, @mimowo mentioned that we could use the (TBA) `successPolicy` on the main driver [as shown in this doc](https://docs.google.com/document/d/1WqjSeFOrMneGS1wlC5cmhtHrpF2rErh-EIfkVN7rBrA/edit). to easily say "when the broker is completed this JobSet is done/successful." But you're right - [this could work too](https://github.com/kubernetes/kubernetes/issues/117600).

So I understand - right now I could develop this / try it out by installing JobSet to my cluster manually. But in the future (how far?) it will ship with Kubernetes? I just subscribed to https://github.com/kubernetes-sigs/jobset/issues/82 so minimally I think I could test it out when that is added. I'm not totally sure which approach is right yet, but it would be fun to test both. I'd argue they should generate a setup that is very similar anyway, with the JobSet having a few more handles to control custom logic and order.

**Comment by vsoch** [comment]
Pinging @grondo and @garlick on this _for discussion next week!_ Please do fun things over the weekend and do not think about Flux!

We experimented today with the following pattern to check for a non zero exit code, and if one was found, to continue the loop:

```bash
# pseudo-code
while true:
   try to connect to the main broker
    - if fails, keep looping
    - if exit with 0, assume success and exit
   always sleep 15
```

With very basic testing, I saw all the pods in the `COMPLETED` state. This was immensely satisfying. But when I scaled it up to a production cluster to test, I saw unexpected behavior - for even a size 2 cluster, the broker and worker would both start, and somehow still appear to be waiting for one another. This was transient, because sometimes it worked, but the first time it didn't, the automated jobs came to a standstill. I stepped back, and then tried a design similar to the first, but with a shorter sleep

```bash
while true:
   try to connect to the main broker
   always sleep 1
```

This actually didn't work either! It was only when I returned to the original design with a longer sleep did I see the pods consistently working as they did before.


```bash
while true:
   try to connect to the main broker
   always sleep 15
```
This seems to be like a tiny bug, and we need to figure out the right way to ensure that retry happens when appropriate, and that (for some cases that I don't understand yet) the broker and worker don't both start, but remain somehow unlinked.

Have a good weekend everyone! :avocado:

**Comment by vsoch** [comment]
Another update to this issue - we were able to somehow close in on part of the reason we see longer creation times than when we didn't have the certificate generator pod. It seems that zeromq has an exponential backoff when it can't connect on first try. So (what I think) is happening is that the zeromq didn't need to wait before for the headless service, because somehow with the certificate generator pod design it was ready to go. Without that, the pods can't always see each other by the time the workers and broker starts, so this exponential backoff was kicking in. When I tested this evening setting a default value in zeromq, this parameter:

![image](https://user-images.githubusercontent.com/814322/235578759-73dd2ca9-107f-4643-b97c-1a65dc176eff.png)

The times decreased from about 140 seconds down to 20. So that doesn't give us all of the time back (before the certificate generator pod was removed we were at 11-12 per run) but it's a big chunk of the way there. What I want to better understand is how/why the headless service was always ready to go in the first setup, but now seems to take longer to be ready (in the ballpark of 5-12 seconds).

**Comment by vsoch** [comment]
Update: zmq connect timeout has been merged into flux! https://github.com/flux-framework/flux-core/pull/5140. This will go into the next release, and I'm going to rebuild a bunch of our containers using the master branch, and then test with different timeouts.

**Comment by vsoch** [comment]
This was fixed last week https://github.com/flux-framework/flux-operator/pull/159
